.TH "aiEntity" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aiEntity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AIEntity\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaiEntity\fP ()"
.br
.ti -1c
.RI "\fB~aiEntity\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDL_Rect \fBai\fP"
.br
.ti -1c
.RI "int \fBspeedX\fP"
.br
.ti -1c
.RI "int \fBspeedY\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.ti -1c
.RI "float \fBrotation\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "aiEntity::aiEntity ()"

.SS "aiEntity::~aiEntity ()"

.SH "Member Data Documentation"
.PP 
.SS "SDL_Rect aiEntity::ai"

.SS "float aiEntity::alpha"

.SS "float aiEntity::rotation"

.SS "int aiEntity::speedX"

.SS "int aiEntity::speedY"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
