.TH "dvar_value" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dvar_value \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBInt\fP"
.br
.ti -1c
.RI "char * \fBString\fP"
.br
.ti -1c
.RI "double \fBDouble\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double dvar_value::Double"

.SS "int64_t dvar_value::Int"

.SS "char* dvar_value::String"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
