.TH "dvar" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dvar \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dvar\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdvar\fP (const char *name, const char *desc, \fBdvar_flag_t\fP flag, \fBdvar_type_t\fP type, \fBdvar_value_t\fP defValue)"
.br
.ti -1c
.RI "\fB~dvar\fP ()"
.br
.ti -1c
.RI "const char * \fBgetName\fP ()"
.br
.ti -1c
.RI "const char * \fBgetDesc\fP ()"
.br
.ti -1c
.RI "\fBdvar_flag_t\fP \fBgetFlag\fP ()"
.br
.ti -1c
.RI "\fBdvar_type_t\fP \fBgetType\fP ()"
.br
.ti -1c
.RI "\fBdvar_value_t\fP \fBgetDefValue\fP ()"
.br
.ti -1c
.RI "\fBdvar_value_t\fP \fBgetValue\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dvar::dvar (const char *name, const char *desc, \fBdvar_flag_t\fPflag, \fBdvar_type_t\fPtype, \fBdvar_value_t\fPdefValue)"

.SS "dvar::~dvar ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBdvar_value_t\fP dvar::getDefValue ()"

.SS "const char * dvar::getDesc ()"

.SS "\fBdvar_flag_t\fP dvar::getFlag ()"

.SS "const char * dvar::getName ()"

.SS "\fBdvar_type_t\fP dvar::getType ()"

.SS "\fBdvar_value_t\fP dvar::getValue ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
