.TH "/home/ludkiller/projects/SuperGuy/src/engine/dvarManager.h" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ludkiller/projects/SuperGuy/src/engine/dvarManager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'dvar\&.h'\fP
.br
\fC#include <boost/ptr_container/ptr_list\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdvarManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
