.TH "enemyAnt" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enemyAnt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enemyAnt\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBenemyAnt\fP ()"
.br
.ti -1c
.RI "\fB~enemyAnt\fP ()"
.br
.ti -1c
.RI "void \fBdestroyMe\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "enemyAnt::enemyAnt ()"

.SS "enemyAnt::~enemyAnt ()"

.SH "Member Function Documentation"
.PP 
.SS "void enemyAnt::destroyMe ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
