.TH "enemyDuck" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enemyDuck \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enemyDuck\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBenemyDuck\fP ()"
.br
.ti -1c
.RI "\fB~enemyDuck\fP ()"
.br
.ti -1c
.RI "void \fBdestroyMe\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "enemyDuck::enemyDuck ()"

.SS "enemyDuck::~enemyDuck ()"

.SH "Member Function Documentation"
.PP 
.SS "void enemyDuck::destroyMe ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
