.TH "/home/ludkiller/projects/SuperGuy/src/enemy/enemyAnt.cpp" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ludkiller/projects/SuperGuy/src/enemy/enemyAnt.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'enemyAnt\&.h'\fP
.br
\fC#include <SDL2/SDL\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
