.TH "/home/ludkiller/projects/SuperGuy/src/enemy/enemyAnt.h" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ludkiller/projects/SuperGuy/src/enemy/enemyAnt.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBenemyAnt\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
