.TH "GameOver" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameOver \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StateMachine\&.h>\fP
.PP
Inherits \fBstateMachine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameOver\fP ()"
.br
.RI "\fIBackground for Message\&. \fP"
.ti -1c
.RI "\fB~GameOver\fP ()"
.br
.RI "\fIConstructor for \fBGameOver\fP\&. \fP"
.ti -1c
.RI "void \fBhandle_events\fP ()"
.br
.RI "\fIDestructor for \fBGameOver\fP\&. \fP"
.ti -1c
.RI "void \fBlogic\fP ()"
.br
.RI "\fIHandle \fBGameOver\fP Events\&. \fP"
.ti -1c
.RI "void \fBrender\fP ()"
.br
.RI "\fIHandle \fBGameOver\fP Logic\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameOver::GameOver ()"

.PP
Background for Message\&. 
.SS "GameOver::~GameOver ()"

.PP
Constructor for \fBGameOver\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "void GameOver::handle_events ()\fC [virtual]\fP"

.PP
Destructor for \fBGameOver\fP\&. 
.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void GameOver::logic ()\fC [virtual]\fP"

.PP
Handle \fBGameOver\fP Events\&. 
.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void GameOver::render ()\fC [virtual]\fP"

.PP
Handle \fBGameOver\fP Logic\&. 
.PP
Reimplemented from \fBstateMachine\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
