.TH "GameOver" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameOver \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StateMachine\&.h>\fP
.PP
Inherits \fBstateMachine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameOver\fP ()"
.br
.ti -1c
.RI "\fB~GameOver\fP ()"
.br
.ti -1c
.RI "void \fBhandle_events\fP ()"
.br
.ti -1c
.RI "void \fBlogic\fP ()"
.br
.RI "\fIHandle events for every state\&. \fP"
.ti -1c
.RI "void \fBrender\fP ()"
.br
.RI "\fIHandle Logic for each state\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameOver::GameOver ()"

.SS "GameOver::~GameOver ()"

.SH "Member Function Documentation"
.PP 
.SS "void GameOver::handle_events ()\fC [virtual]\fP"

.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void GameOver::logic ()\fC [virtual]\fP"

.PP
Handle events for every state\&. 
.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void GameOver::render ()\fC [virtual]\fP"

.PP
Handle Logic for each state\&. 
.PP
Reimplemented from \fBstateMachine\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
