.TH "Intro" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Intro \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StateMachine\&.h>\fP
.PP
Inherits \fBstateMachine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntro\fP ()"
.br
.ti -1c
.RI "\fB~Intro\fP ()"
.br
.ti -1c
.RI "void \fBhandle_events\fP ()"
.br
.ti -1c
.RI "void \fBlogic\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Intro::Intro ()"

.SS "Intro::~Intro ()"

.SH "Member Function Documentation"
.PP 
.SS "void Intro::handle_events ()\fC [virtual]\fP"

.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void Intro::logic ()\fC [virtual]\fP"

.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void Intro::render ()\fC [virtual]\fP"

.PP
Reimplemented from \fBstateMachine\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
