.TH "log" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <log\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlog\fP ()"
.br
.ti -1c
.RI "\fB~log\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBopen\fP (const char *file)"
.br
.ti -1c
.RI "static void \fBclose\fP ()"
.br
.ti -1c
.RI "static void \fBinfo\fP (const char *msg,\&.\&.\&.)"
.br
.ti -1c
.RI "static void \fBerror\fP (const char *msg,\&.\&.\&.)"
.br
.ti -1c
.RI "static void \fBwarning\fP (const char *msg,\&.\&.\&.)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log::log ()"

.SS "log::~log ()"

.SH "Member Function Documentation"
.PP 
.SS "void log::close ()\fC [static]\fP"

.SS "void log::error (const char *msg, \&.\&.\&.)\fC [static]\fP"

.SS "void log::info (const char *msg, \&.\&.\&.)\fC [static]\fP"

.SS "bool log::open (const char *file)\fC [static]\fP"

.SS "void log::warning (const char *msg, \&.\&.\&.)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
