.TH "/home/ludkiller/projects/SuperGuy/src/main.cpp" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ludkiller/projects/SuperGuy/src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include 'log\&.h'\fP
.br
\fC#include 'engine/engine\&.h'\fP
.br
\fC#include 'StateMachine/StateMachine\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
