.TH "Stage1" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stage1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StateMachine\&.h>\fP
.PP
Inherits \fBstateMachine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStage1\fP ()"
.br
.ti -1c
.RI "\fB~Stage1\fP ()"
.br
.ti -1c
.RI "void \fBhandle_events\fP ()"
.br
.ti -1c
.RI "void \fBlogic\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Stage1::Stage1 ()"

.SS "Stage1::~Stage1 ()"

.SH "Member Function Documentation"
.PP 
.SS "void Stage1::handle_events ()\fC [virtual]\fP"

.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void Stage1::logic ()\fC [virtual]\fP"

.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void Stage1::render ()\fC [virtual]\fP"

.PP
Reimplemented from \fBstateMachine\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
