.TH "stateMachine" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stateMachine \- 
.PP
States for State Machine\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StateMachine\&.h>\fP
.PP
Inherited by \fBGameOver\fP, \fBIntro\fP, \fBStage1\fP, and \fBTitle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBhandle_events\fP ()"
.br
.ti -1c
.RI "virtual void \fBlogic\fP ()"
.br
.RI "\fIHandle events for every state\&. \fP"
.ti -1c
.RI "virtual void \fBrender\fP ()"
.br
.RI "\fIHandle Logic for each state\&. \fP"
.ti -1c
.RI "virtual \fB~stateMachine\fP ()"
.br
.RI "\fIHandle rendering for each state\&. \fP"
.ti -1c
.RI "void \fBsetNextState\fP ()"
.br
.RI "\fIDestructor for each state\&. \fP"
.ti -1c
.RI "void \fBchangeState\fP ()"
.br
.RI "\fISets our next state\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
States for State Machine\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual stateMachine::~stateMachine ()\fC [virtual]\fP"

.PP
Handle rendering for each state\&. 
.SH "Member Function Documentation"
.PP 
.SS "void stateMachine::changeState ()"

.PP
Sets our next state\&. 
.SS "virtual void stateMachine::handle_events ()\fC [virtual]\fP"

.PP
Reimplemented in \fBGameOver\fP, \fBStage1\fP, \fBTitle\fP, and \fBIntro\fP\&.
.SS "virtual void stateMachine::logic ()\fC [virtual]\fP"

.PP
Handle events for every state\&. 
.PP
Reimplemented in \fBGameOver\fP, \fBStage1\fP, \fBTitle\fP, and \fBIntro\fP\&.
.SS "virtual void stateMachine::render ()\fC [virtual]\fP"

.PP
Handle Logic for each state\&. 
.PP
Reimplemented in \fBGameOver\fP, \fBStage1\fP, \fBTitle\fP, and \fBIntro\fP\&.
.SS "void stateMachine::setNextState ()"

.PP
Destructor for each state\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
