.TH "/home/ludkiller/projects/SuperGuy/src/StateMachine/StateMachine.cpp" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ludkiller/projects/SuperGuy/src/StateMachine/StateMachine.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'StateMachine\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetNextState\fP (int newState)"
.br
.ti -1c
.RI "void \fBchangeState\fP ()"
.br
.RI "\fISets our next state\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void changeState ()"

.PP
Sets our next state\&. 
.SS "void setNextState (intnewState)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
