.TH "/home/ludkiller/projects/SuperGuy/src/StateMachine/StateMachine.h" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ludkiller/projects/SuperGuy/src/StateMachine/StateMachine.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstateMachine\fP"
.br
.ti -1c
.RI "class \fBIntro\fP"
.br
.ti -1c
.RI "class \fBTitle\fP"
.br
.ti -1c
.RI "class \fBStage1\fP"
.br
.ti -1c
.RI "class \fBGameOver\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSTATES\fP { \fBSTATE_NULL\fP, \fBSTATE_INTRO\fP, \fBSTATE_TITLE\fP, \fBSTATE_STAGE1\fP, \fBSTATE_GAMEOVER\fP, \fBSTATE_QUIT\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSTATES\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISTATE_NULL \fP\fP
.TP
\fB\fISTATE_INTRO \fP\fP
.TP
\fB\fISTATE_TITLE \fP\fP
.TP
\fB\fISTATE_STAGE1 \fP\fP
.TP
\fB\fISTATE_GAMEOVER \fP\fP
.TP
\fB\fISTATE_QUIT \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
