.TH "/home/ludkiller/projects/SuperGuy/src/StateMachine/StateMachine.h" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ludkiller/projects/SuperGuy/src/StateMachine/StateMachine.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstateMachine\fP"
.br
.ti -1c
.RI "class \fBIntro\fP"
.br
.ti -1c
.RI "class \fBTitle\fP"
.br
.ti -1c
.RI "class \fBOverWorld\fP"
.br
.ti -1c
.RI "class \fBStage1\fP"
.br
.ti -1c
.RI "class \fBGameOver\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSTATES\fP { \fBSTATE_NULL\fP, \fBSTATE_INTRO\fP, \fBSTATE_TITLE\fP, \fBSTATE_OVERWORLD\fP, \fBSTATE_STAGE1\fP, \fBSTATE_STAGE2\fP, \fBSTATE_GAMEOVER\fP, \fBSTATE_QUIT\fP }"
.br
.RI "\fIStates for State Machine\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetNextState\fP (int newState)"
.br
.ti -1c
.RI "void \fBchangeState\fP ()"
.br
.RI "\fISets our next state\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBstateID\fP = \fBSTATE_NULL\fP"
.br
.ti -1c
.RI "int \fBnextState\fP = \fBSTATE_NULL\fP"
.br
.ti -1c
.RI "\fBstateMachine\fP * \fBcurrentState\fP = NULL"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSTATES\fP"

.PP
States for State Machine\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISTATE_NULL \fP\fP
.TP
\fB\fISTATE_INTRO \fP\fP
NULL STATE\&. 
.TP
\fB\fISTATE_TITLE \fP\fP
INTRO or SPLASH SCREEN STATE\&. 
.TP
\fB\fISTATE_OVERWORLD \fP\fP
TITLE STATE\&. 
.TP
\fB\fISTATE_STAGE1 \fP\fP
.TP
\fB\fISTATE_STAGE2 \fP\fP
STAGE1 can add other Stages later similar to STAGE1\&. 
.TP
\fB\fISTATE_GAMEOVER \fP\fP
.TP
\fB\fISTATE_QUIT \fP\fP
GAMEOVER self explanatory\&. QUIT After Game over or random quit ;3 
.SH "Function Documentation"
.PP 
.SS "void changeState ()"

.PP
Sets our next state\&. 
.SS "void setNextState (intnewState)"

.SH "Variable Documentation"
.PP 
.SS "\fBstateMachine\fP* currentState = NULL"

.SS "int nextState = \fBSTATE_NULL\fP"

.SS "int stateID = \fBSTATE_NULL\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
