.TH "texture" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
texture \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <texture\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtexture\fP (const char *file, int count)"
.br
.ti -1c
.RI "\fBtexture\fP (SDL_Surface *tex)"
.br
.ti -1c
.RI "\fB~texture\fP ()"
.br
.ti -1c
.RI "\fBtexture\fP * \fBgetTextureAtPos\fP (int pos)"
.br
.ti -1c
.RI "SDL_Surface * \fBgetTexture\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "texture::texture (const char *file, intcount)"

.SS "texture::texture (SDL_Surface *tex)"

.SS "texture::~texture ()"

.SH "Member Function Documentation"
.PP 
.SS "SDL_Surface * texture::getTexture ()"

.SS "\fBtexture\fP * texture::getTextureAtPos (intpos)"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
