.TH "/home/ludkiller/projects/SuperGuy/src/engine/texture.cpp" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ludkiller/projects/SuperGuy/src/engine/texture.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'texture\&.h'\fP
.br
\fC#include '\&.\&./log\&.h'\fP
.br
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include <SDL2/SDL_image\&.h>\fP
.br
\fC#include <cmath>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
