.TH "Title" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Title \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StateMachine\&.h>\fP
.PP
Inherits \fBstateMachine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTitle\fP ()"
.br
.ti -1c
.RI "\fB~Title\fP ()"
.br
.ti -1c
.RI "void \fBhandle_events\fP ()"
.br
.ti -1c
.RI "void \fBlogic\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Title::Title ()"

.SS "Title::~Title ()"

.SH "Member Function Documentation"
.PP 
.SS "void Title::handle_events ()\fC [virtual]\fP"

.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void Title::logic ()\fC [virtual]\fP"

.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void Title::render ()\fC [virtual]\fP"

.PP
Reimplemented from \fBstateMachine\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
