.TH "Title" 3 "Mon Mar 25 2013" "SuperGuy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Title \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StateMachine\&.h>\fP
.PP
Inherits \fBstateMachine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTitle\fP ()"
.br
.RI "\fI\fBTitle\fP Message\&. \fP"
.ti -1c
.RI "\fB~Title\fP ()"
.br
.RI "\fIConstructor for \fBTitle\fP\&. \fP"
.ti -1c
.RI "void \fBhandle_events\fP ()"
.br
.RI "\fIDestructor for \fBTitle\fP\&. \fP"
.ti -1c
.RI "void \fBlogic\fP ()"
.br
.RI "\fIHandle \fBTitle\fP Events\&. \fP"
.ti -1c
.RI "void \fBrender\fP ()"
.br
.RI "\fIHandle \fBTitle\fP Logic\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Title::Title ()"

.PP
\fBTitle\fP Message\&. 
.SS "Title::~Title ()"

.PP
Constructor for \fBTitle\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Title::handle_events ()\fC [virtual]\fP"

.PP
Destructor for \fBTitle\fP\&. 
.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void Title::logic ()\fC [virtual]\fP"

.PP
Handle \fBTitle\fP Events\&. 
.PP
Reimplemented from \fBstateMachine\fP\&.
.SS "void Title::render ()\fC [virtual]\fP"

.PP
Handle \fBTitle\fP Logic\&. 
.PP
Reimplemented from \fBstateMachine\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperGuy from the source code\&.
